[project]
name = "py-node-exporter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "prometheus-client>=0.23.1",
    "psutil>=7.2.0",
]
